POST http://localhost:3000/
Content-Type: application/json

{
    "startDate": "2016-01-25",
    "endDate": "2019-01-25",
    "minCount": 2700,
    "maxCount": 4500
    
}

###

POST http://localhost:3000/new
Content-Type: application/json

{
    "createdAt": "2018-01-02",
    "totalCount": 2750
}